### ISSUE TITLE
Compiled SPMM on U200

### ISSUE THREAD

**Issue by lloo099** [linghaosong/Sextans#4]
Hi, As I compiled ur spmm kernel for U200. And it generated host file. 

Could u provide some information about how to define these values:
./host <XCLBIN File> [matrix A file] [N] [ALPHA] [BETA] [rp_time]

how to use matrix A file? and could u give a example
rp_time is stand for ?

Thanks,

**Comment by linghaosong** [comment]
[matrix A file] is a matrix market (.mtx) file. rp_time is a test parameter you can just ignore it.
Here is a simple running case.
1. download a sparse matrix in (.mtx) file, such as
`wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/p2p-Gnutella04.tar.gz`
then uncompress it
2. run
`./host p2p-Gnutella04.mtx 16 0.85 -2.5`

More details are coming soon. Stay tuned!

**Comment by linghaosong** [comment]
> Hi, As I compiled ur spmm kernel for U200. And it generated host file.
> 
> Could u provide some information about how to define these values: ./host [matrix A file] [N] [ALPHA] [BETA] [rp_time]
> 
> how to use matrix A file? and could u give a example rp_time is stand for ?
> 
> Thanks,

[matrix A file] is a matrix market (.mtx) file. rp_time is a test parameter you can just ignore it.
Here is a simple run example.
1. download a sparse matrix in (.mtx) file, such as
`wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/p2p-Gnutella04.tar.gz`
then uncompress it
2. run
`./host p2p-Gnutella04.mtx 16 0.85 -2.5`

More details are coming soon. Stay tuned!
